name: CyberGridSim
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - networkx=2.7.1
  - numpy-base=1.21.5
  - pip
  - python=3.10.4
  - rich=12.5.1
  - pip:
    - numba==0.55.1
    - pandas==1.4.3
    - pandapower==2.10.1
    - pip==21.2.4
    - scipy==1.7.3
